"""Abstract protocol definitions for memory subsystem."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class LongTermMemoryProtocol(Protocol):
    """Protocol for long-term memory backends."""

    async def store(self, content: str, metadata: dict[str, Any]) -> str: ...
    async def search(self, query: str, limit: int = 10) -> list[dict[str, Any]]: ...
    async def get(self, memory_id: str) -> dict[str, Any] | None: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def close(self) -> None: ...
