import type { DomainConfig } from "../../types";

export const selfEvolutionDomain: DomainConfig = {
    id: "self-evolution",
    title: "Self-Evolution & Security",
    description: "Monitor autonomous recon gathering, tuning proposals, and self-improvement cycles generated by the heuristic engine.",
    operations: [
        {
            id: "get_active_recon",
            title: "Active Recon & Security Strings",
            description: "Get the status of currently running intelligence gathering or hacking loops.",
            method: "GET",
            path: "/v1/operations/hub"
        },
        {
            id: "list_proposals",
            title: "Evolution Proposals",
            description: "View self-improvement proposals (config calibrations) generated by the tuning loop. Filter by status: pending_approval, applied, proposal_only, dry_run, skipped.",
            method: "GET",
            path: "/v1/improvements/proposals"
        },
        {
            id: "generate_proposal",
            title: "Generate Improvement Proposal",
            description: "Trigger the tuning loop sandbox to compute a new calibration proposal without mutating production state.",
            method: "POST",
            path: "/v1/improvements/proposals/generate"
        },
        {
            id: "tuning_status",
            title: "Tuning Loop Status",
            description: "View the current tuning loop configuration and last cycle result.",
            method: "GET",
            path: "/v1/improvements/tuning/status"
        }
    ]
};
