#!/usr/bin/env bash
set -euo pipefail

# Docker Compose E2E smoke test
# Boots the API stack (api + infra deps), waits for health, runs basic
# endpoint checks, then tears down.  Designed to run in CI or locally.
#
# Usage:
#   scripts/docker-smoke-test.sh [compose-file]
#
# Default compose file: engine/docker-compose.yml

COMPOSE_FILE="${1:-engine/docker-compose.yml}"
MAX_WAIT=120  # seconds to wait for API health
API_URL="http://localhost:8000"

# The compose file is relative to the repo root.  Ensure we are there.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

cleanup() {
    echo "==> Tearing down..."
    docker compose -f "$COMPOSE_FILE" down -v --remove-orphans 2>&1 || true
    # Remove temporary .env if we created one
    if [ "${_CREATED_TEMP_ENV:-}" = "1" ]; then
        rm -f engine/.env
    fi
}
trap cleanup EXIT

# The api service expects env_file: .env in engine/.  If none exists,
# create a minimal one so compose does not error out.
_CREATED_TEMP_ENV=0
if [ ! -f engine/.env ]; then
    echo "==> Creating minimal engine/.env for smoke test..."
    cat > engine/.env <<'ENVEOF'
# Auto-generated by docker-smoke-test.sh -- safe to delete
ENVIRONMENT=test
JWT_SECRET=smoke-test-jwt-secret-not-for-production
API_SECRET_KEY=smoke-test-api-key-not-for-production
ENVEOF
    _CREATED_TEMP_ENV=1
fi

echo "==> Starting Docker Compose stack (api + infra only)..."
# Start only the API and its declared infrastructure dependencies.
# This skips the frontend build (which needs repo-root context and npm)
# and any profiled services (ollama, devbox, n8n, airllm).
docker compose -f "$COMPOSE_FILE" up -d --build \
    postgres redis nats searxng api 2>&1

echo "==> Waiting for API health (max ${MAX_WAIT}s)..."
for i in $(seq 1 "$MAX_WAIT"); do
    # Use the lightweight liveness probe first to detect process readiness.
    if curl -sf "${API_URL}/healthz" > /dev/null 2>&1; then
        echo "    Liveness probe passed at ${i}s"
        break
    fi
    if [ "$i" -eq "$MAX_WAIT" ]; then
        echo "    TIMEOUT: API did not become healthy in ${MAX_WAIT}s"
        echo ""
        echo "==> Container status:"
        docker compose -f "$COMPOSE_FILE" ps 2>&1 || true
        echo ""
        echo "==> API logs (last 80 lines):"
        docker compose -f "$COMPOSE_FILE" logs --tail=80 api 2>&1 || true
        exit 1
    fi
    sleep 1
done

FAILURES=0

run_check() {
    local name="$1"
    local url="$2"
    local expect_code="${3:-200}"

    local http_code
    local body
    body=$(curl -sf -w "\n%{http_code}" "$url" 2>&1) || true
    http_code=$(echo "$body" | tail -1)
    body=$(echo "$body" | sed '$d')

    if [ "$http_code" = "$expect_code" ]; then
        echo "    [PASS] $name (HTTP $http_code)"
    else
        echo "    [FAIL] $name (expected HTTP $expect_code, got $http_code)"
        FAILURES=$((FAILURES + 1))
    fi

    # Print a brief snippet of the response for debugging
    if [ -n "$body" ]; then
        echo "           $(echo "$body" | head -c 200)"
    fi
}

echo ""
echo "==> Running smoke checks..."

# 1. Lightweight liveness probe
run_check "GET /healthz" "${API_URL}/healthz"

# 2. Full health endpoint (returns JSON with dependency status)
run_check "GET /health" "${API_URL}/health"

# 3. Kubernetes readiness probe (may be 503 if Ollama is absent -- that is
#    expected in CI where Ollama is not started)
echo "    (readiness probe -- 503 is acceptable when Ollama is not running)"
READYZ_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${API_URL}/readyz" 2>/dev/null || echo "000")
if [ "$READYZ_CODE" = "200" ] || [ "$READYZ_CODE" = "503" ]; then
    echo "    [PASS] GET /readyz (HTTP $READYZ_CODE -- endpoint responded)"
else
    echo "    [FAIL] GET /readyz (expected 200 or 503, got $READYZ_CODE)"
    FAILURES=$((FAILURES + 1))
fi

# 4. OpenAPI docs
run_check "GET /docs" "${API_URL}/docs"

# 5. Prometheus metrics endpoint
METRICS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${API_URL}/metrics" 2>/dev/null || echo "000")
if [ "$METRICS_CODE" = "200" ] || [ "$METRICS_CODE" = "404" ]; then
    # 404 is acceptable if the metrics middleware is disabled in test mode
    echo "    [PASS] GET /metrics (HTTP $METRICS_CODE)"
else
    echo "    [FAIL] GET /metrics (expected 200 or 404, got $METRICS_CODE)"
    FAILURES=$((FAILURES + 1))
fi

echo ""
if [ "$FAILURES" -eq 0 ]; then
    echo "==> All smoke checks passed!"
else
    echo "==> FAILED: $FAILURES check(s) did not pass."
    echo ""
    echo "==> API logs (last 40 lines):"
    docker compose -f "$COMPOSE_FILE" logs --tail=40 api 2>&1 || true
    exit 1
fi
