#!/usr/bin/env python3
"""verify_model_cache_recipe.py -- issue #33 (R42 cache_recipe) validator.

Consumes a MODEL_CACHE_RECIPE manifest path and validates either (a) the
manifest's internal consistency offline (`--dry-run`, the default and the
mode used by the PR-gate validator R42 in scripts/validate_pr_brutal_honesty.py)
or (b) the recipe's actual reproducibility by materializing each artifact
and bit-for-bit comparing the regenerated hash against the declared
hash_sha256 (`--reproduce`, the mode for the Tier B human reviewer who
explicitly wants to confirm the recipe is real).

Why this script exists: the translation-swarm post-mortem found that
`out/translation_models/` was full of patched configs, manually-converted
CT2 bundles, and environment-specific truststore fixes -- none committed
to the repo, none documented, and none reproducible on a fresh checkout.
A reviewer reading the PR body could not tell whether the cache held real
production weights or a hand-tweaked local artifact that nobody else
could regenerate. R42 closes that loop: every gitignored artifact cited
under EVIDENCE: must carry a recipe that, in dry-run mode, structurally
documents how it was built; and, in --reproduce mode, actually rebuilds
the bytes deterministically.

Exit codes:
  0  success (manifest validates in dry-run; or all artifacts reproduce
              bit-for-bit in --reproduce).
  1  schema fail (manifest does not validate against
              schemas/model-cache-recipe.schema.json).
  2  patch-file missing (a patches[].path does not exist OR is empty).
  3  patch-step-vs-patches mismatch (download_command contains a
              patch-step marker but patches[] is empty -- the recipe is
              incomplete; L4 partial-as-complete).
  4  gitignore mismatch (cache_path is NOT covered by any .gitignore
              line resolving inside the repo -- the artifact is either
              committed (and the recipe is unnecessary) or the path is
              outside the repo and the recipe cannot prove anything).
  5  reproduce hash mismatch (--reproduce mode: regenerated bytes hash
              differs from declared hash_sha256).
  6  reproduce network / exec failure (--reproduce mode: download_command
              or verification_command exited non-zero, or DNS / TLS
              resolution failed).

Dry-run is the default because the PR-gate validator R42 calls this
script through subprocess and a network-touching default would make the
gate flaky and slow. --reproduce is the human knob (mirrors v3.3
smoke.sh's --api-only / runtime split).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Optional

# ============================================================================
# Exit codes (kept as module constants so tests can import the same names).
# ============================================================================

EXIT_OK = 0
EXIT_SCHEMA = 1
EXIT_PATCH_FILE_MISSING = 2
EXIT_PATCH_STEP_MISMATCH = 3
EXIT_GITIGNORE_MISMATCH = 4
EXIT_REPRODUCE_HASH_MISMATCH = 5
EXIT_REPRODUCE_NETWORK = 6


# ============================================================================
# Paths.
# ============================================================================

# scripts/verify_model_cache_recipe.py -> v3.5/ root.
SCRIPT_DIR = Path(__file__).resolve().parent
V35_ROOT = SCRIPT_DIR.parent
SCHEMA_PATH = (
    V35_ROOT
    / "_internal"
    / "conventions"
    / "brutal-honesty-kit"
    / "v3.5"
    / "schemas"
    / "model-cache-recipe.schema.json"
)


# ============================================================================
# Patch-step heuristic (R42c).
# ============================================================================

# Markers that indicate the download_command mutates the artifact in
# place. If any marker matches, patches[] MUST be non-empty (otherwise
# the recipe describes mutation without listing what was mutated -- L4
# partial-as-complete). The patterns are anchored at word boundaries
# where it matters so a benign substring (e.g. `psed` containing `sed`)
# does not false-fire.
PATCH_STEP_MARKERS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bpatch\s+-p[0-9]+\b"),
    re.compile(r"\bsed\s+-i\b"),
    re.compile(r"\bgit\s+apply\b"),
    re.compile(
        r"\bpython[0-9.]*\s+-c\s+[\"'].*open\s*\([^)]*['\"]w['\"]"
    ),
    re.compile(r"\bperl\s+-i\b"),
)


def _command_has_patch_step(command: str) -> Optional[str]:
    """Return the matched marker token if `command` contains a patch step.

    Returns None if no marker matches. Returns the matched substring
    (for use in the operator-facing error message) when one matches.
    """
    for pattern in PATCH_STEP_MARKERS:
        m = pattern.search(command)
        if m:
            return m.group(0)
    return None


# ============================================================================
# .gitignore reader (R42d).
# ============================================================================


def _load_gitignore_patterns(repo_root: Path) -> list[str]:
    """Read repo-root .gitignore and return non-comment / non-blank lines.

    Returns an empty list when the file is absent (rare in healthy repos
    but not impossible -- e.g. a fresh `git init`). The patterns are
    matched as glob substrings against the cache_path; we deliberately
    do NOT implement full git pathspec semantics here -- that would
    require a `git check-ignore` subprocess that depends on the working
    tree state, which is brittle in a PR-gate context. The substring
    match is conservative (it errs toward declaring a path covered when
    a leading `/` or `**` would also have covered it).
    """
    gitignore_path = repo_root / ".gitignore"
    if not gitignore_path.exists():
        return []
    try:
        text = gitignore_path.read_text(encoding="utf-8")
    except OSError:
        return []
    patterns: list[str] = []
    for raw_line in text.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # Strip a leading `/` (anchored-to-root pattern) and a leading
        # `!` (negation). The substring match is conservative either
        # way.
        if stripped.startswith("!"):
            stripped = stripped[1:].strip()
        if stripped.startswith("/"):
            stripped = stripped[1:]
        # Drop the trailing `/` (directory marker) -- substring match
        # then matches `models/foo/file.bin` against `models`.
        stripped = stripped.rstrip("/")
        if stripped:
            patterns.append(stripped)
    return patterns


def _cache_path_covered_by_gitignore(
    cache_path: str, gitignore_patterns: list[str]
) -> bool:
    """Conservative substring / glob match.

    Returns True if any pattern is a substring of cache_path OR
    cache_path matches the pattern as a fnmatch glob. False otherwise.
    Empty pattern list -> always False (no .gitignore = no coverage).
    """
    if not gitignore_patterns:
        return False
    # Normalize separators so a Windows backslash path matches a forward-
    # slash .gitignore entry.
    normalized = cache_path.replace("\\", "/")
    import fnmatch

    for pattern in gitignore_patterns:
        # Direct substring match (covers `models/` against
        # `models/opus-mt-en-de/pytorch_model.bin`).
        if pattern in normalized:
            return True
        # Glob match (covers `*.bin` against the same path).
        if fnmatch.fnmatch(normalized, pattern):
            return True
        if fnmatch.fnmatch(normalized, f"*{pattern}*"):
            return True
    return False


# ============================================================================
# Schema loader.
# ============================================================================


def _load_schema() -> Optional[dict]:
    if not SCHEMA_PATH.exists():
        return None
    try:
        return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


# ============================================================================
# Manifest validator (dry-run).
# ============================================================================


def validate_dry_run(
    manifest: dict,
    manifest_path: Path,
    repo_root: Path,
) -> tuple[int, list[str]]:
    """Run the offline checks: schema + patch-file existence + patch-step
    heuristic + gitignore coverage. Return (exit_code, messages).

    The first failing prong determines the exit code (the order matches
    the exit-code numbering in the module docstring). Subsequent prongs
    still run so the operator sees every diagnostic in one pass; the
    return code is the FIRST failure's code.
    """
    messages: list[str] = []
    first_failure: Optional[int] = None

    # Prong 1 -- schema validation.
    schema = _load_schema()
    if schema is None:
        messages.append(
            f"R42-schema: cannot load schema at {SCHEMA_PATH} -- "
            "either the v3.5 tree is missing or the file is malformed."
        )
        return EXIT_SCHEMA, messages
    try:
        import jsonschema

        jsonschema.validate(instance=manifest, schema=schema)
    except ImportError:
        # Soft-skip with stderr breadcrumb -- the PR-gate validator
        # already prints a setup hint when jsonschema is absent.
        messages.append(
            "R42-schema: jsonschema not installed -- skipping schema "
            "validation. Install with `pip install jsonschema` to "
            "enable R42 schema enforcement."
        )
    except jsonschema.ValidationError as exc:  # type: ignore[attr-defined]
        path_str = ".".join(str(p) for p in exc.absolute_path) or "<root>"
        messages.append(
            f"R42-schema: manifest at {manifest_path} fails schema: "
            f"{exc.message} (path={path_str})."
        )
        if first_failure is None:
            first_failure = EXIT_SCHEMA

    # Prong 2 -- patch-file existence.
    artifacts = manifest.get("artifacts", [])
    if not isinstance(artifacts, list):
        artifacts = []
    for idx, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            continue
        patches = artifact.get("patches", [])
        if not isinstance(patches, list):
            continue
        for pidx, patch in enumerate(patches):
            if not isinstance(patch, dict):
                continue
            patch_rel = patch.get("path")
            if not isinstance(patch_rel, str) or not patch_rel:
                continue
            patch_abs = repo_root / patch_rel
            if not patch_abs.exists():
                messages.append(
                    f"R42-patch-file: artifacts[{idx}].patches[{pidx}].path "
                    f"= {patch_rel!r} does not exist (resolved to "
                    f"{patch_abs}). A unified-diff patch listed in the "
                    "recipe MUST be a checked-in file the reviewer can "
                    "open; free-text patches are L13."
                )
                if first_failure is None:
                    first_failure = EXIT_PATCH_FILE_MISSING
                continue
            try:
                if patch_abs.stat().st_size == 0:
                    messages.append(
                        f"R42-patch-file: artifacts[{idx}].patches[{pidx}].path "
                        f"= {patch_rel!r} is empty (0 bytes). An empty "
                        "patch claims a mutation that does not exist."
                    )
                    if first_failure is None:
                        first_failure = EXIT_PATCH_FILE_MISSING
            except OSError:
                pass

    # Prong 3 -- patch-step-vs-patches heuristic.
    for idx, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            continue
        download_command = artifact.get("download_command", "")
        if not isinstance(download_command, str):
            continue
        marker = _command_has_patch_step(download_command)
        if marker is None:
            continue
        patches = artifact.get("patches", [])
        if not isinstance(patches, list) or not patches:
            messages.append(
                f"R42-patch-step: artifacts[{idx}].download_command "
                f"contains the patch-step marker {marker!r} but "
                "patches[] is empty. A command that mutates the "
                "downloaded artifact MUST list every mutation as a "
                "checked-in unified diff (L4 partial-as-complete close: "
                "the recipe claims to materialize the artifact but the "
                "mutations are undocumented)."
            )
            if first_failure is None:
                first_failure = EXIT_PATCH_STEP_MISMATCH

    # Prong 4 -- .gitignore coverage.
    gitignore_patterns = _load_gitignore_patterns(repo_root)
    for idx, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            continue
        cache_path = artifact.get("cache_path")
        if not isinstance(cache_path, str) or not cache_path:
            continue
        if not _cache_path_covered_by_gitignore(cache_path, gitignore_patterns):
            messages.append(
                f"R42-gitignore: artifacts[{idx}].cache_path = "
                f"{cache_path!r} is NOT covered by any .gitignore line "
                "in the repo root. Either (a) the artifact is committed "
                "and the recipe is unnecessary, or (b) the path is "
                "outside the repo and the recipe cannot prove "
                "anything. A recipe exists to make an INVISIBLE artifact "
                "reproducible -- a visible artifact does not need one."
            )
            if first_failure is None:
                first_failure = EXIT_GITIGNORE_MISMATCH

    if first_failure is None:
        return EXIT_OK, messages
    return first_failure, messages


# ============================================================================
# Reproduce mode (network).
# ============================================================================


def _resolve_dns_or_fail(source_url: str) -> Optional[str]:
    """Best-effort DNS resolution of the host part of source_url.

    Returns None on success (host resolves), or an error string on
    failure. Per RFC 6761, `.invalid` TLDs are guaranteed never to
    resolve -- the test harness mocks socket.gethostbyname so the
    fixture's `.invalid` URL fails deterministically here.
    """
    import socket
    from urllib.parse import urlparse

    try:
        parsed = urlparse(source_url)
    except Exception as exc:
        return f"urlparse failed: {exc}"
    host = parsed.hostname
    if not host:
        return f"no hostname in source_url={source_url!r}"
    try:
        socket.gethostbyname(host)
    except socket.gaierror as exc:
        return (
            f"DNS resolution failed for host={host!r} "
            f"(socket.gaierror: {exc})"
        )
    except Exception as exc:  # pragma: no cover -- defensive
        return f"DNS lookup error for host={host!r}: {exc}"
    return None


def validate_reproduce(
    manifest: dict,
    manifest_path: Path,
    repo_root: Path,
) -> tuple[int, list[str]]:
    """Run the network-touching checks. Returns (exit_code, messages).

    For each artifact:
      1. If source_url is present, resolve its hostname (fail with
         EXIT_REPRODUCE_NETWORK on DNS error -- this is the
         `.invalid` TLD deterministic-failure path).
      2. Materialize a temporary CACHE dir.
      3. Run download_command in a subprocess with CACHE_PATH=<tmp>.
         Non-zero exit -> EXIT_REPRODUCE_NETWORK.
      4. Apply each patch via `git apply --directory <tmp>`. Non-zero
         exit -> EXIT_REPRODUCE_NETWORK (patches that don't apply are
         operationally indistinguishable from a network failure --
         the recipe is broken either way).
      5. Run verification_command, capture stdout, compare to
         hash_sha256. Mismatch -> EXIT_REPRODUCE_HASH_MISMATCH.
    """
    messages: list[str] = []
    first_failure: Optional[int] = None
    artifacts = manifest.get("artifacts", [])
    if not isinstance(artifacts, list):
        return EXIT_OK, messages
    for idx, artifact in enumerate(artifacts):
        if not isinstance(artifact, dict):
            continue
        source_url = artifact.get("source_url")
        if isinstance(source_url, str) and source_url:
            dns_error = _resolve_dns_or_fail(source_url)
            if dns_error is not None:
                messages.append(
                    f"R42-reproduce: artifacts[{idx}] DNS resolution "
                    f"failed: {dns_error}. The recipe cannot be "
                    "regenerated from this checkout; either the upstream "
                    "is gone or the network path is blocked."
                )
                if first_failure is None:
                    first_failure = EXIT_REPRODUCE_NETWORK
                continue
        download_command = artifact.get("download_command", "")
        verification_command = artifact.get("verification_command", "")
        declared_hash = artifact.get("hash_sha256", "")
        if not (
            isinstance(download_command, str)
            and isinstance(verification_command, str)
            and isinstance(declared_hash, str)
        ):
            continue
        with tempfile.TemporaryDirectory(
            prefix="bhk-cache-recipe-"
        ) as tmpdir:
            env = os.environ.copy()
            env["CACHE_PATH"] = tmpdir
            try:
                result = subprocess.run(
                    download_command,
                    shell=True,
                    cwd=str(repo_root),
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=600,
                )
                if result.returncode != 0:
                    messages.append(
                        f"R42-reproduce: artifacts[{idx}].download_command "
                        f"exited {result.returncode}. stderr (first 200 "
                        f"chars): {result.stderr[:200]!r}"
                    )
                    if first_failure is None:
                        first_failure = EXIT_REPRODUCE_NETWORK
                    continue
            except (subprocess.TimeoutExpired, OSError) as exc:
                messages.append(
                    f"R42-reproduce: artifacts[{idx}].download_command "
                    f"raised {type(exc).__name__}: {exc}."
                )
                if first_failure is None:
                    first_failure = EXIT_REPRODUCE_NETWORK
                continue
            patches = artifact.get("patches", [])
            if isinstance(patches, list):
                for pidx, patch in enumerate(patches):
                    if not isinstance(patch, dict):
                        continue
                    patch_rel = patch.get("path", "")
                    if not isinstance(patch_rel, str) or not patch_rel:
                        continue
                    patch_abs = repo_root / patch_rel
                    if not patch_abs.exists():
                        messages.append(
                            f"R42-reproduce: artifacts[{idx}]."
                            f"patches[{pidx}].path = {patch_rel!r} does "
                            "not exist (caught earlier by dry-run; "
                            "repeated here because --reproduce ran on a "
                            "manifest that should have been rejected at "
                            "PR-gate time)."
                        )
                        if first_failure is None:
                            first_failure = EXIT_PATCH_FILE_MISSING
                        continue
                    apply_result = subprocess.run(
                        [
                            "git",
                            "apply",
                            "--directory",
                            tmpdir,
                            str(patch_abs),
                        ],
                        cwd=str(repo_root),
                        capture_output=True,
                        text=True,
                    )
                    if apply_result.returncode != 0:
                        messages.append(
                            f"R42-reproduce: artifacts[{idx}]."
                            f"patches[{pidx}] failed to apply (git apply "
                            f"exited {apply_result.returncode}). stderr "
                            f"(first 200 chars): "
                            f"{apply_result.stderr[:200]!r}"
                        )
                        if first_failure is None:
                            first_failure = EXIT_REPRODUCE_NETWORK
            try:
                verify_result = subprocess.run(
                    verification_command,
                    shell=True,
                    cwd=str(repo_root),
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=120,
                )
                if verify_result.returncode != 0:
                    messages.append(
                        f"R42-reproduce: artifacts[{idx}]."
                        f"verification_command exited "
                        f"{verify_result.returncode}. stderr (first 200 "
                        f"chars): {verify_result.stderr[:200]!r}"
                    )
                    if first_failure is None:
                        first_failure = EXIT_REPRODUCE_NETWORK
                    continue
            except (subprocess.TimeoutExpired, OSError) as exc:
                messages.append(
                    f"R42-reproduce: artifacts[{idx}]."
                    f"verification_command raised "
                    f"{type(exc).__name__}: {exc}."
                )
                if first_failure is None:
                    first_failure = EXIT_REPRODUCE_NETWORK
                continue
            # Compare the first 64 hex chars of trimmed stdout to the
            # declared hash. `sha256sum file` prints `<hash>  <path>`;
            # take the first whitespace-delimited token.
            stdout_trimmed = verify_result.stdout.strip().split()
            actual_hash = (
                stdout_trimmed[0].lower() if stdout_trimmed else ""
            )
            if actual_hash != declared_hash.lower():
                messages.append(
                    f"R42-reproduce: artifacts[{idx}] hash mismatch. "
                    f"Declared {declared_hash}, regenerated "
                    f"{actual_hash!r}. The recipe is broken: either the "
                    "upstream changed since the hash was recorded, or "
                    "the patches no longer apply cleanly, or the "
                    "verification_command is wrong."
                )
                if first_failure is None:
                    first_failure = EXIT_REPRODUCE_HASH_MISMATCH

    if first_failure is None:
        return EXIT_OK, messages
    return first_failure, messages


# ============================================================================
# CLI.
# ============================================================================


def _detect_repo_root(start: Path) -> Path:
    """Walk upward from `start` looking for a `.git` dir; return the
    parent of the .git dir, or `start` if none found."""
    cur = start.resolve()
    for _ in range(40):  # generous walk limit
        if (cur / ".git").exists():
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    return start.resolve()


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="verify_model_cache_recipe.py",
        description=(
            "Issue #33 (R42 cache_recipe) -- validate a "
            "MODEL_CACHE_RECIPE manifest. --dry-run is the offline "
            "default (used by the PR-gate validator); --reproduce "
            "actually materializes each artifact and verifies hashes "
            "(network-touching, for human reviewers)."
        ),
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help=(
            "Path to a MODEL_CACHE_RECIPE manifest JSON file. "
            "Validated against schemas/model-cache-recipe.schema.json."
        ),
    )
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument(
        "--dry-run",
        action="store_true",
        default=True,
        help=(
            "[default] Validate manifest schema + patch-file existence "
            "+ patch-step heuristic + .gitignore coverage. Offline. "
            "Used by the PR-gate validator R42."
        ),
    )
    mode_group.add_argument(
        "--reproduce",
        action="store_true",
        help=(
            "Materialize each artifact in a temporary CACHE_PATH, "
            "apply patches, run verification_command, and compare the "
            "regenerated hash to hash_sha256 bit-for-bit. "
            "Network-touching; for human Tier B reviewers."
        ),
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help=(
            "Repository root (used for resolving patches[].path and "
            "reading .gitignore). Defaults to the nearest ancestor of "
            "--manifest that contains a .git directory."
        ),
    )
    args = parser.parse_args(argv)

    manifest_path = Path(args.manifest).resolve()
    if not manifest_path.exists():
        sys.stderr.write(
            f"R42: manifest path {manifest_path} does not exist.\n"
        )
        return EXIT_SCHEMA
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        sys.stderr.write(
            f"R42: cannot parse manifest at {manifest_path}: "
            f"{type(exc).__name__}: {exc}\n"
        )
        return EXIT_SCHEMA

    if args.repo_root:
        repo_root = Path(args.repo_root).resolve()
    else:
        repo_root = _detect_repo_root(manifest_path.parent)

    if args.reproduce:
        exit_code, messages = validate_reproduce(
            manifest, manifest_path, repo_root
        )
    else:
        exit_code, messages = validate_dry_run(
            manifest, manifest_path, repo_root
        )

    for msg in messages:
        sys.stderr.write(msg + "\n")
    if exit_code == EXIT_OK:
        sys.stdout.write(
            f"R42: manifest at {manifest_path} OK "
            f"({'reproduce' if args.reproduce else 'dry-run'} mode).\n"
        )
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
