"""agent33 bootstrap — generate .env.local with sensible defaults."""

from __future__ import annotations

import secrets
import string
from pathlib import Path

import typer

app = typer.Typer(help="Bootstrap AGENT-33 configuration.")


def _generate_secret(length: int = 64) -> str:
    """Generate a cryptographically secure random secret string."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _generate_api_key() -> str:
    """Generate a dev API key in the format agent33_dev_<random>."""
    return f"agent33_dev_{secrets.token_urlsafe(24)}"


ENV_TEMPLATE = """\
# AGENT-33 Configuration -- generated by `agent33 bootstrap`
# WARNING: This file is for development/lite mode only.
# Do NOT commit this file to version control.
# For production, set all variables explicitly via environment or secrets manager.

# Mode (lite | standard | enterprise)
AGENT33_MODE=lite

# Security -- auto-generated, rotate before any multi-user or public deployment
JWT_SECRET={jwt_secret}

# Default dev API key -- only valid in lite/dev mode
AGENT33_DEV_API_KEY={api_key}

# LLM provider -- set ONE of the following:
# OPENAI_API_KEY=sk-...
# OPENROUTER_API_KEY=sk-or-...
# ANTHROPIC_API_KEY=sk-ant-...
# Or use Ollama (start with: ollama serve)
OLLAMA_BASE_URL=http://localhost:11434
# Leave blank to use the server-side default. Examples:
# DEFAULT_MODEL=openrouter/auto
# DEFAULT_MODEL=openrouter/openai/gpt-5.2
DEFAULT_MODEL=llama3.2:3b
OLLAMA_DEFAULT_MODEL=llama3.2:3b

# Server
HOST=0.0.0.0
PORT=8000

# Logging
LOG_LEVEL=INFO
"""


def _bootstrap_generate(*, output: Path, force: bool) -> None:
    """Core bootstrap logic shared between CLI entry points."""
    if output.exists() and not force:
        typer.echo(f"  {output} already exists. Use --force to overwrite.", err=True)
        raise typer.Exit(1)

    jwt_secret = _generate_secret(64)
    api_key = _generate_api_key()

    content = ENV_TEMPLATE.format(jwt_secret=jwt_secret, api_key=api_key)
    output.write_text(content, encoding="utf-8")

    typer.echo(f"\n  Generated {output}")
    typer.echo(f"  JWT_SECRET: {jwt_secret[:8]}... (64 chars)")
    typer.echo(f"  Dev API key: {api_key[:20]}...")
    typer.echo()
    typer.echo("  Next steps:")
    typer.echo("    1. Review .env.local and set your LLM provider key")
    typer.echo("    2. Run: agent33 start")
    typer.echo()
    typer.echo("  WARNING: Never commit .env.local to version control.")
    typer.echo("  WARNING: Never use auto-generated secrets in production.\n")


@app.command()
def bootstrap(
    output: Path = typer.Option(  # noqa: B008
        Path(".env.local"),  # noqa: B008
        "--output",
        "-o",
        help="Output file path.",
    ),
    force: bool = typer.Option(  # noqa: B008
        False,
        "--force",
        "-f",
        help="Overwrite existing file.",
    ),
) -> None:
    """Generate a .env.local file with secure defaults for local development.

    Generates a cryptographically random JWT_SECRET and dev API key.
    The output file is safe for local dev/lite mode -- do NOT use in production.
    """
    _bootstrap_generate(output=output, force=force)
